import { StoreProvider } from "@/redux/store/StoreProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
       <main> {children}</main>
        </StoreProvider>
      </body>
    </html>
  );
}
